### ISSUE TITLE
MultipleSelectDropdown not rendered correctly

### ISSUE THREAD

**Issue by DrillSergeant** [neos/form-builder#7] opened 2017-10-16 09:38 UTC
Only the one option is visible.

Steps to reproduce:
* insert an MultipleSelectDropdown-Node
* add multiple options to it

Expected result:
Multiple options are available to chose from

Actial result:
Only one option is visible

Screenshot: 
![pasted image at 2017_10_13 02_54 pm](https://user-images.githubusercontent.com/883552/31605451-8995ab38-b266-11e7-9aab-0dd885a6aba5.png)

**Comment by bwaidelich** [comment] 2017-10-16 15:29
@DrillSergeant Thanks for the report. Unfortunately I can't reproduce this issue:
As soon as I set the value of a new SelectOption and hit `Apply` the main stage is reloaded and the new select option is visible.
The structure tree needs a manual refresh in order for the new option to be selectable, but that's covered with #8

**Comment by DrillSergeant** [comment] 2017-10-17 08:43
@bwaidelich I did some more testing and now I know when it happens:
When you add options and don't enter a value for them (only a label). After I added values, the options appeared.
I tried to remove the value again from an option but the field is marked as required (which makes sense), so I cannot empty an existing value anymore.
Is it possible to require the option right after it has been created?

**Comment by bwaidelich** [comment] 2017-10-17 12:10
Mh, even without a value (= empty string) the option is rendered for me. But, yes, it behaves a bit flakey.
Once I try to set the label though without setting the value I get an error:
![image](https://user-images.githubusercontent.com/307571/31664084-641325e6-b344-11e7-8983-38e1999e8c38.png)

> Is it possible to require the option right after it has been created?

That's what the `required` flag should do.. But we can't really intercept the node from being created with the current UI. With the new UI we can use the new `creationDialog` for this.

Two measurements for now that I can think of:
1. specify a default value for the `SelectOption` nodes, so they will never be empty
2. document how to create a custom (Multi-)Select Form Element with custom options

**Comment by DrillSergeant** [comment] 2017-10-17 13:40
Thanks for your feedback. Default value is a good solution for me, I think I will go that way once I need those elements in a project.
I think we can close this issue as it this is not part of the form-builder-package anymore. Right?

**Comment by bwaidelich** [comment] 2017-10-24 15:38
@DrillSergeant 3 PRs for you: #10 #11 #12  ;)

**Comment by bwaidelich** [comment] 2018-02-26 13:01
Closing as the related PRs have been merged in the meantime.
Unfortunately using the `creationDialog` alone won't work. But for custom implementations it can be enabled with https://github.com/bwaidelich/Wwwision.Neos.CreationDialogProperties

**Closed by bwaidelich** 2018-02-26 13:01 UTC
Labels: bug
